version: "2.12"

services:
  client:
    build: ./packages/client
    ports:
      - 5173:80
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
  server:
    build: ./packages/server
    ports:
      - 3001:3001
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: Password123#@!
      MYSQL_DATABASE: web_authn_demo
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m