version: "2.12"

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: Password123#@!
      MYSQL_DATABASE: web_authn_demo